export const cards = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "390501",
        name: "The Blu Umbrella",
        uuid: "491c45b8-42ca-4d76-9ecb-c503f3ab84e4",
        city: "98",
        area: "Mango",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "qm4fnlqlzxzgdjiwbd1v",
        cuisines: [
          "North Indian",
          "Chinese"
        ],
        tags: [],
        costForTwo: 50000,
        costForTwoString: "₹500 FOR TWO",
        deliveryTime: 39,
        minDeliveryTime: 39,
        maxDeliveryTime: 39,
        slaString: "39 MINS",
        lastMileTravel: 2.299999952316284,
        slugs: {
          restaurant: "the-blu-umbrella-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "Dimna Rd, Kukudungri, Mango, Jamshedpur, Jharkhand 831012, India",
        locality: "Mango",
        parentId: 257200,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "2.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "390501",
          deliveryTime: 39,
          minDeliveryTime: 39,
          maxDeliveryTime: 39,
          lastMileTravel: 2.299999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "678407",
        name: "Atrium Boutique Hotel\t",
        uuid: "99a953a9-47c0-4005-a39b-4d45047e4212",
        city: "98",
        area: "Sakchi",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "uxdng6rjg9j9jqwgv0xh",
        cuisines: [
          "Indian"
        ],
        tags: [],
        costForTwo: 39900,
        costForTwoString: "₹399 FOR TWO",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        slaString: "45 MINS",
        lastMileTravel: 5.800000190734863,
        slugs: {
          restaurant: "atrium-boutique-hotel-sakchi-sakchi",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "89,PANORAMA CENTER, WATER WORKS ROAD SAKCHI, Sakchi, Jamshedpur Urban, Purbi Singhbhum, Jharkhand - 831001",
        locality: "Purbi Singhbhum",
        parentId: 405488,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
            {
              meta: "20% off on all orders",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
            {
              meta: "20% off on all orders",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "20% OFF",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
            {
              meta: "20% off on all orders",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED"
          }
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5969770~p=19~eid=00000186-9d02-2d2f-49f1-7ca900861365",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "5.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "678407",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          lastMileTravel: 5.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: true,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "683027",
        name: "Mystique Grill",
        uuid: "22a015cb-601d-418c-b45a-cd06a4092e45",
        city: "98",
        area: "Mango",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "e565c4ad2e3450129c54c8d333557bdc",
        cuisines: [
          "Chinese",
          "Tandoor",
          "Continental"
        ],
        tags: [],
        costForTwo: 29900,
        costForTwoString: "₹299 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 2,
        slugs: {
          restaurant: "mystique-grill-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "2ND FLOOR, YASHODA COMPLEX, DIMNA ROAD, MANGO, Mango Municipality Word Nos 10, Muncipality, Purbi Singhbhum, Jharkhand - 831012",
        locality: "Dimna Road",
        parentId: 407634,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "683027",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 2,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: true,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "473609",
        name: "Al Baik the taste of middle east",
        uuid: "06fe3294-4555-4e69-9959-999fc68e6d79",
        city: "98",
        area: "Old Purualia Road",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "o9vvasnaqvqf2lcusyyf",
        cuisines: [
          "Snacks",
          "Biryani",
          "American"
        ],
        tags: [],
        costForTwo: 29900,
        costForTwoString: "₹299 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "al-baik-the-test-of-middle-east-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "R6R4+J5P, Jawahar Nagar, Mango, Jamshedpur, Jharkhand 832110, India",
        locality: "Mango",
        parentId: 369915,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "473609",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "164297",
        name: "American Waffle House",
        uuid: "6ae9ea1f-563d-4053-8cde-a814e055fd0d",
        city: "98",
        area: "Ambagan",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "miuzceqi6fzxdensnxba",
        cuisines: [
          "Waffle",
          "Ice Cream"
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 5.900000095367432,
        slugs: {
          restaurant: "americal-waffles-sakchi-sakchi",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "Sakchi, Aambagarn, beside keventers",
        locality: "Sakchi",
        parentId: 5523,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED"
          }
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6090934~p=22~eid=00000186-9d02-2d2f-49f1-7caa0086161b",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "5.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "164297",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 5.900000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "400732",
        name: "A J Smart Food",
        uuid: "504edb3e-ff35-4535-880a-cfb263a71adf",
        city: "98",
        area: "Sonari",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "ppzrcchhvyycjpmjnl2n",
        cuisines: [
          "Chinese",
          "Indian"
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 44,
        minDeliveryTime: 44,
        maxDeliveryTime: 44,
        slaString: "44 MINS",
        lastMileTravel: 2.200000047683716,
        slugs: {
          restaurant: "a-j-smart-food-sonari-sonari",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "Shiv Kumar Asthali Appt., NH - 33, Flat No. F/3, 3rd Floor, B - Block, Besides Motor World NH - 33, Mango, Jamshedpur, Jharkhand - 831012.",
        locality: "Sonari",
        parentId: 238314,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "2.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "400732",
          deliveryTime: 44,
          minDeliveryTime: 44,
          maxDeliveryTime: 44,
          lastMileTravel: 2.200000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "660052",
        name: "The Hilton Bawarchi",
        uuid: "cbee58c0-1a6f-49e1-bf62-1388a077a166",
        city: "98",
        area: "Mango",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "2a302f105ec371d077438b301b23ccf8",
        cuisines: [
          "North Indian",
          "Chinese",
          "Fast Food",
          "Kebabs",
          "Seafood",
        ],
        tags: [],
        costForTwo: 44000,
        costForTwoString: "₹440 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 2.799999952316284,
        slugs: {
          restaurant: "the-hilton-bawarchi-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "Akash Heights, Purulia Rd, near Kerla Public School, Mango, Jamshedpur, Jharkhand 832110, India",
        locality: "Purulia Rd",
        parentId: 396397,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "2.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "660052",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 2.799999952316284,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "633873",
        name: "Butterfly Food Works",
        uuid: "ecefa4bb-f887-4d76-b442-32b44437deba",
        city: "98",
        area: "Sakchi",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "tmycxgnbbgvmjadudbo6",
        cuisines: [
          "Mughlai",
          "Chinese",
          "North Indian"
        ],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "₹450 FOR TWO",
        deliveryTime: 47,
        minDeliveryTime: 47,
        maxDeliveryTime: 47,
        slaString: "47 MINS",
        lastMileTravel: 7.300000190734863,
        slugs: {
          restaurant: "butterfly-food-works-sakchi-sakchi",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "R628+29R, New Sitaram Dera, Golmuri, Jamshedpur, Jharkhand 831009, India",
        locality: "Golmuri",
        parentId: 381055,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED"
          }
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5902347~p=25~eid=00000186-9d02-2d2f-49f1-7cab00861974",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "7.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "633873",
          deliveryTime: 47,
          minDeliveryTime: 47,
          maxDeliveryTime: 47,
          lastMileTravel: 7.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "141038",
        name: "Kolkata Arsalan Biryani",
        uuid: "7a44a814-805d-43cc-b673-feaaf194ea05",
        city: "98",
        area: "Mango",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "fy2bof3tovvkibgcamkf",
        cuisines: [
          "Indian",
          "Tandoor"
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "kolkata-arshlan-biryani-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "17 PURULIA RD, ANJAN COMPLEX, MANGO, JAMSHEDPUR",
        locality: "MANGO",
        parentId: 119863,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "141038",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "214722",
        name: "Mini Punjab",
        uuid: "1aef7313-1319-4d7d-b127-9b589a3c8584",
        city: "98",
        area: "Mango",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "rnaghfuyprtptbdmzz87",
        cuisines: [
          "Biryani",
          "North Indian",
          "Chinese",
          "Tandoor",
          "Snacks",
          "Fast Food",
          "Punjabi",
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant: "mini-punjab-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "Mini Punjab, Baliguma, Mango, Jamshedpur, Jharkhand, India",
        locality: "Mango",
        parentId: 7952,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "20% off",
          shortDescriptionList: [
            {
              meta: "20% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹50 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "20% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹50 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "2.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "214722",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "150497",
        name: "National Bakery",
        uuid: "24623bde-4827-408e-be50-6303ec857ad3",
        city: "98",
        area: "Agrico",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "kb6vrstmuk07mirkqh05",
        cuisines: [
          "Bakery",
          "Snacks",
          "Desserts"
        ],
        tags: [],
        costForTwo: 39900,
        costForTwoString: "₹399 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 6.800000190734863,
        slugs: {
          restaurant: "national-bakery-sakchi-sakchi",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "725, NEW SITARAM DERA, SAKCHI, JAMSHEDPUR",
        locality: "Sakchi",
        parentId: 144458,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "20% off",
          shortDescriptionList: [
            {
              meta: "20% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹50 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "20% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹50 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED"
          }
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6091660~p=28~eid=00000186-9d02-2d2f-49f1-7cac00861c1b",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "6.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "150497",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 6.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "389458",
        name: "The Biryani Boxx",
        uuid: "47042d21-5d7f-41f1-9032-ff71be92bb71",
        city: "98",
        area: "Mango",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "alxzyidy7zj8dwyytq8u",
        cuisines: [
          "Biryani",
          "Kebabs"
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 44,
        minDeliveryTime: 44,
        maxDeliveryTime: 44,
        slaString: "44 MINS",
        lastMileTravel: 2.5999999046325684,
        slugs: {
          restaurant: "the-biryani-boxx-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "LAZIZ PIZZA, GF - 17, THE DIGNITY, NEAR ROAD NO. 14, JWAHARNAGAR, MANGO, JAMSHEDPUR",
        locality: "Mango",
        parentId: 205402,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "389458",
          deliveryTime: 44,
          minDeliveryTime: 44,
          maxDeliveryTime: 44,
          lastMileTravel: 2.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "595893",
        name: "KN FAST FOOD",
        uuid: "dc707f3e-8104-458a-8e18-603faad2e687",
        city: "98",
        area: "Mango",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "c0ddnvpa0nfqifuynh1b",
        cuisines: [
          "Chinese",
          "Fast Food"
        ],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 2.5999999046325684,
        slugs: {
          restaurant: "kn-fast-food-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "R6HF+5F2, Dimna Rd, near Neelkanth colony, beside Purno deep complex, Adarsh Nagar, Mango, Jamshedpur, Jharkhand 831001, India",
        locality: "Adarsh Nagar",
        parentId: 356382,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "2.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "595893",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 2.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "129693",
        name: "Ravi Bakers",
        uuid: "fcefff96-37af-4b6a-85b3-ef146ad7e1e4",
        city: "98",
        area: "Bistupur",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "d6m14p6epr2talfu0syz",
        cuisines: [
          "Bakery",
          "Snacks",
          "Pizzas",
          "Burgers"
        ],
        tags: [],
        costForTwo: 39900,
        costForTwoString: "₹399 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 8.699999809265137,
        slugs: {
          restaurant: "ravi-bakers-dhatkidih-bistupur",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "CENTRAL PLAZA , ST MILE ROAD, A BLOCK , DHATKIDIH",
        locality: "bistupur",
        parentId: 167637,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED"
          }
        ],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=6086626~p=31~eid=00000186-9d02-2d2f-49f1-7cad00861f42",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "8.6 kms",
        hasSurge: false,
        sla: {
          restaurantId: "129693",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 8.699999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "3.9",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "378128",
        name: "BRUNCH ITALIANO",
        uuid: "69f6465d-ac73-4613-97d9-527a05a045ae",
        city: "98",
        area: "Mango",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "hmkagbopednm1qolck4e",
        cuisines: [
          "Bakery"
        ],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 2.700000047683716,
        slugs: {
          restaurant: "brunch-italiano-mango-mango",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "NEAR VISHAL MEGA MART DIMNA ROAD MANGO OPPOSITE MOONCITY",
        locality: "Mango",
        parentId: 50559,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "2.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "378128",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 2.700000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "583220",
        name: "Grameen Kulfi",
        uuid: "22b44f13-2ce7-4858-ab5d-49bb5dd9331f",
        city: "98",
        area: "Gunomoy madhusudan Tower",
        totalRatingsString: "20+ ratings",
        cloudinaryImageId: "uxdng6rjg9j9jqwgv0xh",
        cuisines: [
          "Ice Cream",
          "Desserts"
        ],
        tags: [],
        costForTwo: 12000,
        costForTwoString: "₹120 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "grameen-kulfi-telco-colony-telco",
          city: "jamshedpur",
        },
        cityState: "98",
        address: "Shop no_5,Gunomoy Madhusudan, Tower Near- Mango Bridge - Jamshedpur -831012",
        locality: "Mango Bridge",
        parentId: 12175,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "FREE DELIVERY",
          shortDescriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [
            {
              meta: "Free Delivery",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "FREE DELIVERY",
              discountType: "FREE_DELIVERY",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: "",
          title: "",
          amount: "",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [], textBased: [], textExtendedBadges: []
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "583220",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.8",
        totalRatings: 20,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
]
export const SWIGGY_API_URL = "https://corsproxy.io/?https://www.swiggy.com/dapi/restaurants/list/v5?lat=21.1702401&lng=72.83106070000001&page_type=DESKTOP_WEB_LISTING"
export const IMG_CDN_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"
// Swiggy API to get Restaurant Menu data with corsproxy
export const SWIGGY_MENU_API_URL =
"https://corsproxy.io/?https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=21.1702401&lng=72.83106070000001&&submitAction=ENTER&restaurantId=";
// menu items api card type key
export const MENU_ITEM_TYPE_KEY =
  "type.googleapis.com/swiggy.presentation.food.v2.ItemCategory";
export const RESTAURANT_TYPE_KEY =
  "type.googleapis.com/swiggy.presentation.food.v2.Restaurant";

  
